package com.shopacc.backend.enums;

public enum AuditAction {

    USER_LOGIN,
    USER_REGISTER,

    USER_PURCHASE,
    USER_VIEW_SECRET,

    ADMIN_CREATE_LISTING,
    ADMIN_UPDATE_LISTING,
    ADMIN_DELETE_LISTING,
    ADMIN_UPDATE_LISTING_STATUS,
    ADMIN_UPDATE_LISTING_FEATURED,

    ADMIN_CREATE_CATEGORY,
    ADMIN_UPDATE_CATEGORY,
    ADMIN_DELETE_CATEGORY,

    ADMIN_ADJUST_BALANCE,
    ADMIN_APPROVE_TRANSACTION,
    ADMIN_REJECT_TRANSACTION,

    ADMIN_UPLOAD_LISTING_IMAGE,
    ADMIN_DELETE_LISTING_IMAGE
}